# Generated by Django 4.1 on 2023-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklesson',
            name='lesson_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracklesson',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
