# Generated by Django 4.1 on 2023-08-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_alter_tracklesson_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tracklesson',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
