# Generated by Django 4.1 on 2023-12-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_iframe',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
