# Generated by Django 4.1 on 2024-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_event_map_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ispaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='required_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
