# Generated by Django 4.1 on 2024-01-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0012_usercoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('eduction', models.CharField(choices=[('SEE', 'SEE'), ('+2', '+2'), ('Bachelors', 'Bachelors')], max_length=20)),
                ('School_or_College_name', models.CharField(choices=[('SEE', 'SEE'), ('+2', '+2'), ('Bachelors', 'Bachelors')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
